SAMPS = ["a.chr21", "b.chr21"]

rule all:
    input:
        "data/multiqc/multiqc_report.html",

rule fastqc:
    input:
        expand(["ngs-test-data/reads/{sample}.1.fq", "ngs-test-data/reads/{sample}.2.fq"], sample=SAMPS)
    output:
        expand(["data/fastqc/{sample}.1_fastqc.html","data/fastqc/{sample}.2_fastqc.html"], sample=SAMPS)
    conda:
        "envs/qc.yml"
    params:
        threads = "4"
    shell:
        "fastqc -o data/fastqc -t {params.threads} {input}"

rule multiqc:
    input:
        expand(["data/fastqc/{sample}.1_fastqc.html","data/fastqc/{sample}.2_fastqc.html"], sample=SAMPS)
    output:
        "data/multiqc/multiqc_report.html"
    conda:
        "envs/qc.yml"
    shell:
        "multiqc data -o data/multiqc "